### ISSUE TITLE
Tracking issue: complete command support

### ISSUE THREAD

**Issue by caelunshun** [feather-rs/feather#229]
#209 added initial support for commands using [`lieutenant`](https://github.com/feather-rs/lieutenant) and implemented `/tp` and `/gamemode`. What's left to do:

* Implement [all commands in Vanilla](https://minecraft.gamepedia.com/Commands#List_and_summary_of_commands) (only those present in Java Edition)
* Ensure that messages are consistent with Vanilla (this is certainly not the case right now)
* Implement [target selector arguments](https://minecraft.gamepedia.com/Commands#Target_selector_arguments)
* [Send the command node graph to players upon joining](https://wiki.vg/Protocol#Declare_Commands)

For newcomers to the project, implementing a command is a good way to start. The basic process is:
* Locate the Minecraft Wiki page for the command and read through it, so you understand the command well (skip any Bedrock-specific sections).
* Go into `server/commands/src/impls.rs` and implement the command.
  * The `tp` implementation is a good example of how a command could be implemented.
  * If you need a new argument type (for example, a parsed gamemode or a UUID), implement it in `server/commands/src/arguments.rs`. `EntitySelector` and `ParsedGamemode` are useful examples to see how this is done.

If you need any help, you are welcome to ask as many questions as you need on our Discord server :)

**Comment by amberkowalski** [comment]
I'm currently working on the [tell](https://minecraft.gamepedia.com/Commands/tell) command.

**Comment by onbjerg** [comment]
Java Edition vanilla commands list:

- [ ] [`/attribute`](https://minecraft.gamepedia.com/Commands/attribute)
- [ ] [`/locatebiome`](https://minecraft.gamepedia.com/Commands/locatebiome)
- [ ] [`/advancement`](https://minecraft.gamepedia.com/Commands/advancement)
- [ ] [`/ban`](https://minecraft.gamepedia.com/Commands/ban)
- [ ] [`/ban-ip`](https://minecraft.gamepedia.com/Commands/ban-ip)
- [ ] [`/banlist`](https://minecraft.gamepedia.com/Commands/banlist)
- [ ] [`/bossbar`](https://minecraft.gamepedia.com/Commands/bossbar)
- [ ] [`/clear`](https://minecraft.gamepedia.com/Commands/clear)
- [ ] [`/clone`](https://minecraft.gamepedia.com/Commands/clone)
- [ ] [`/data`](https://minecraft.gamepedia.com/Commands/data)
- [ ] [`/datapack`](https://minecraft.gamepedia.com/Commands/datapack)
- [ ] [`/debug`](https://minecraft.gamepedia.com/Commands/debug)
- [ ] [`/defaultgamemode`](https://minecraft.gamepedia.com/Commands/defaultgamemode)
- [ ] [`/deop`](https://minecraft.gamepedia.com/Commands/deop)
- [ ] [`/difficulty`](https://minecraft.gamepedia.com/Commands/difficulty)
- [ ] [`/effect`](https://minecraft.gamepedia.com/Commands/effect)
- [ ] [`/enchant`](https://minecraft.gamepedia.com/Commands/enchant)
- [ ] [`/execute`](https://minecraft.gamepedia.com/Commands/execute)
- [ ] [`/experience`](https://minecraft.gamepedia.com/Commands/experience)
- [ ] [`/fill`](https://minecraft.gamepedia.com/Commands/fill)
- [ ] [`/forceload`](https://minecraft.gamepedia.com/Commands/forceload)
- [ ] [`/function`](https://minecraft.gamepedia.com/Commands/function)
- [x] [`/gamemode`](https://minecraft.gamepedia.com/Commands/gamemode)
- [ ] [`/gamerule`](https://minecraft.gamepedia.com/Commands/gamerule)
- [ ] [`/give`](https://minecraft.gamepedia.com/Commands/give)
- [ ] [`/help`](https://minecraft.gamepedia.com/Commands/help)
- [ ] [`/kick`](https://minecraft.gamepedia.com/Commands/kick)
- [ ] [`/kill`](https://minecraft.gamepedia.com/Commands/kill)
- [ ] [`/list`](https://minecraft.gamepedia.com/Commands/list)
- [ ] [`/locate`](https://minecraft.gamepedia.com/Commands/locate)
- [ ] [`/loot`](https://minecraft.gamepedia.com/Commands/loot)
- [ ] [`/op`](https://minecraft.gamepedia.com/Commands/op)
- [ ] [`/pardon`](https://minecraft.gamepedia.com/Commands/pardon)
- [ ] [`/particle`](https://minecraft.gamepedia.com/Commands/particle)
- [ ] [`/playsound`](https://minecraft.gamepedia.com/Commands/playsound)
- [ ] [`/publish`](https://minecraft.gamepedia.com/Commands/publish)
- [ ] [`/recipe`](https://minecraft.gamepedia.com/Commands/recipe)
- [ ] [`/reload`](https://minecraft.gamepedia.com/Commands/reload)
- [ ] [`/replaceitem`](https://minecraft.gamepedia.com/Commands/replaceitem)
- [ ] [`/save-all`](https://minecraft.gamepedia.com/Commands/save-all)
- [ ] [`/save-off`](https://minecraft.gamepedia.com/Commands/save-off)
- [ ] [`/save-on`](https://minecraft.gamepedia.com/Commands/save-on)
- [x] [`/say`](https://minecraft.gamepedia.com/Commands/say)
- [ ] [`/schedule`](https://minecraft.gamepedia.com/Commands/schedule)
- [ ] [`/scoreboard`](https://minecraft.gamepedia.com/Commands/scoreboard)
- [ ] [`/seed`](https://minecraft.gamepedia.com/Commands/seed)
- [ ] [`/setblock`](https://minecraft.gamepedia.com/Commands/setblock)
- [ ] [`/setidletime`](https://minecraft.gamepedia.com/Commands/setidletime)
- [ ] [`/setworldspawn`](https://minecraft.gamepedia.com/Commands/setworldspawn)
- [ ] [`/spawnpoint`](https://minecraft.gamepedia.com/Commands/spawnpoint)
- [ ] [`/spectate`](https://minecraft.gamepedia.com/Commands/spectate)
- [ ] [`/spreadplayers`](https://minecraft.gamepedia.com/Commands/spreadplayers)
- [ ] [`/stop`](https://minecraft.gamepedia.com/Commands/stop)
- [ ] [`/stopsound`](https://minecraft.gamepedia.com/Commands/stopsound)
- [ ] [`/summon`](https://minecraft.gamepedia.com/Commands/summon)
- [ ] [`/tag`](https://minecraft.gamepedia.com/Commands/tag)
- [ ] [`/team`](https://minecraft.gamepedia.com/Commands/team)
- [ ] [`/teammsg`](https://minecraft.gamepedia.com/Commands/teammsg)
- [x] [`/teleport`](https://minecraft.gamepedia.com/Commands/teleport)
- [x] [`/tell`](https://minecraft.gamepedia.com/Commands/tell)
- [ ] [`/tellraw`](https://minecraft.gamepedia.com/Commands/tellraw)
- [ ] [`/time`](https://minecraft.gamepedia.com/Commands/time)
- [ ] [`/title`](https://minecraft.gamepedia.com/Commands/title)
- [x] [`/tp`](https://minecraft.gamepedia.com/Commands/tp)
- [ ] [`/trigger`](https://minecraft.gamepedia.com/Commands/trigger)
- [x] [`/w`](https://minecraft.gamepedia.com/Commands/w)
- [ ] [`/weather`](https://minecraft.gamepedia.com/Commands/weather)
- [ ] [`/whitelist`](https://minecraft.gamepedia.com/Commands/whitelist)
- [ ] [`/worldborder`](https://minecraft.gamepedia.com/Commands/worldborder)
- [ ] [`/xp`](https://minecraft.gamepedia.com/Commands/xp)

**Comment by BuggStream** [comment]
I think I will start working on the `/weather` command.

**Comment by Miro-Andrin** [comment]
I have written some python code to parse the commands.json file that you can generate from the server jar. Using this i have generated (almost) all the functions one would need to implement to reach 99% vanilla command support.

The included file [commands.txt](https://github.com/feather-rs/feather/files/5001254/commands.txt) contains (almost) all the functions that one would eventually need to implement. As an example here is one of the xp commands. For now i have them returning a "not implemented msg", but we would have to implement their functionality here. 

    #[command(usage="xp add <targets> <amount> points")]
    pub fn xp2(
        targets : MultiplePlayers, amount : IntegerArgument
    ) -> anyhow::Result<()>{
        if let Some(mut sender_message_receiver) = ctx.world.try_get_mut::<MessageReceiver>(ctx.sender)
        {
            let return_text = Text::from("This command \"xp add <targets> <amount> points\" is not implemented in this version of feather.").gray().italic();
            sender_message_receiver.send(return_text);
        }
        return Ok(())
    }



The included file [parsers.txt](https://github.com/feather-rs/feather/files/5001235/parsers.txt) has a list of the 50 to 60 ish parsers that the commands in commands.rs assume we have implemented. 
As an example here is the parser for BlockPos. 

    #[derive(Debug, Error)]
    pub enum BlockPosParseError {}

    #[derive(Clone, Debug)]
    pub struct BlockPos(pub String);

    impl ArgumentKind<CommandCtx> for BlockPos {
        type ParseError = BlockPosParseError;

        fn satisfies<'a>(_ctx: &CommandCtx, input: &mut Input<'a>) -> bool {
            input.advance_until(" ");
            //TODO 
            true
        }

        fn parse<'a>(_ctx: &CommandCtx, input: &mut Input<'a>) -> Result<Self, Self::ParseError> {
            let text = input.advance_until(" ");
            //TODO
            Ok(BlockPos(text.to_owned()))
        }
    }


With my scripts i am able to load two different versions of minecrafts commands.json file and see what changes have been made. This would make it possible to track changes in vanilla commands, and get a "diff" for every release, stating what rust code needs to be added/removed. I want to know if the maintainers would be interested in including the generated files. I am not suggesting we add python as part of the build process, just the generated code. If you want to include the generated code, then i am going to spend some time improving the script and release it, and also spend the time creating a pull request. 


[parsers.txt](https://github.com/feather-rs/feather/files/5001235/parsers.txt)

[commands.txt](https://github.com/feather-rs/feather/files/5001254/commands.txt)

**Comment by caelunshun** [comment]
@Miro-Andrin Wow, that's impressive, thanks for this! I'd be happy to include these generated files as part of the commands crate. Including the generator script in this repo seems like a good idea, in case we want to regenerate the code for some reason, but it doesn't have to be a mandatory build dependency.

**Comment by CDFN** [comment]
`stop` command is already implemented (https://github.com/feather-rs/feather/pull/260), mark it as done please :)
